title: ダイスキーBlog
description: ''
author: ぷーざ
lang: ja
timezone: Asia/Tokyo
url: https://blog.misskey.delmulin.com
baseurl: ""

permalink: /articles/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

markdown: kramdown
kramdown:
  input: GFM

collections:
  drafts:
    output: false

exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - scaffolds
  - themes
  - _config.hexo.yml
  - source
  - public
  - README.md
  - docs
